"""empty message

Revision ID: 29d76a476c70
Revises: None
Create Date: 2014-12-02 02:02:11.548064

"""

# revision identifiers, used by Alembic.
revision = '29d76a476c70'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=True),
    sa.Column('compound_weight', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drugs')
    ### end Alembic commands ###
